line_word_pipeline_config: config/yolo_inference.yaml
syntax_encoder_weights: models/embedder.pt
embeddings: models/train-embeddings.json
classifier_weights: models/word_classifier.pt
labels: models/train-labels.json
device: cpu
