SEED: 42
MARGIN: 2
MARGIN_THRESHOLD: 2
EMBED_DIM: 32
IMG_SIZE: 120
IMG_FORMAT: RGB
DATASET_PATH: "datasets/word_dataset"
SAVE_PATH: "runs/syntax_embedding"
PRETRAINED: # "runs/syntax_embedding/2025-01-12 16_36_45/repeat-1/model.pth"
REPEAT: 1

SIMPLE_TRAIN:
  STEPS_PER_EPOCH: 400
  BATCH_SIZE: 16
  LR: 0.00003
  EPOCHS: 400
  BALANCED: True

HARD_TRAIN:
  STEPS_PER_EPOCH: 400
  BATCH_SIZE: 16
  LR: 0.000001
  EPOCHS: 20
  STR_DIST_THRESHOLD: 1
  BALANCED: True
  REPEAT: 0
