SEED: 42
MARGIN: 2
MARGIN_THRESHOLD: 8
EMBED_DIM: 32
IMG_SIZE: 120
IMG_FORMAT: RGB
DATASET_PATH: "datasets/word_dataset"
SAVE_PATH: "runs/syntax_embedding"
PRETRAINED:
REPEAT: 4

SIMPLE_TRAIN:
  STEPS_PER_EPOCH: 400
  BATCH_SIZE: 16
  LR: 0.0001
  EPOCHS: 100
  BALANCED: True

HARD_TRAIN:
  STEPS_PER_EPOCH: 400
  BATCH_SIZE: 16
  LR: 0.000001
  EPOCHS: 20
  STR_DIST_THRESHOLD: 1
  BALANCED: False
  REPEAT: 0
