SEED: 42
MARGIN: 2
EMBED_DIM: 32
STEPS_PER_EPOCH: 400
IMG_SIZE: 120
IMG_FORMAT: RGB
BATCH_SIZE: 8
DATASET_PATH: "datasets/word_dataset"
SAVE_PATH: "runs/syntax_embedding"
PRETRAINED: "runs/syntax_embedding/2024-12-29 22_06_57/model.pth"
LR: 0.0003
EPOCHS: 100
