data: "../yamls/lines_obb_data.yaml"
epochs: 400
imgsz: 700
batch: 4
box: 9
cls: 1.5
dfl: 1.3
optimizer: "Adam"
rect: True
single_cls: True
workers: 1
hsv_h: 0.0
hsv_s: 0.0
hsv_v: 0.0
translate: 0.1
scale: 0.1
fliplr: 0.0
mosaic: 0.0
erasing: 0.0
crop_fraction: 0.1
lr0: 0.002
lrf: 0.001
